/**
 * Default Stack/Env bank — system-agnostic catalogs + era recipes.
 * Every term appears in exactly ONE kind (no cross-category overlap).
 * Beefed for any domain/era; recipes rotate so projects never look identical.
 */

import type { CatalogEntry, EraRecipe, StackEnvBankDoc } from "./types";

/** Build catalog with forced unique terms across kinds. */
function entry(
  term: string,
  kind: CatalogEntry["kind"],
  opts?: Partial<CatalogEntry>
): CatalogEntry {
  return { term, kind, ...opts };
}

/** Timeless / era-agnostic entry (any decade, any domain profile). */
function tEntry(
  term: string,
  kind: CatalogEntry["kind"],
  opts?: Partial<CatalogEntry>
): CatalogEntry {
  return { term, kind, timeless: true, ...opts };
}

/**
 * TOOLS — products, languages, modules you deliver (Tech Stack lane).
 * System-agnostic + common enterprise nouns.
 */
const TOOLS: CatalogEntry[] = [
  // Languages / data
  entry("SQL", "tool", { timeless: true }),
  entry("T-SQL", "tool", { aliases: ["TSQL"], eraMin: 1995 }),
  entry("PL/SQL", "tool", { aliases: ["PLSQL"], eraMin: 1991 }),
  entry("Python", "tool", { eraMin: 1995 }),
  entry("Java", "tool", { timeless: true, eraMin: 1995 }),
  entry("Scala", "tool", { eraMin: 2004 }),
  entry("R", "tool", { eraMin: 1995 }),
  entry("ABAP", "tool", { eraMin: 1983 }),
  entry("JavaScript", "tool", { aliases: ["JS"], eraMin: 1995 }),
  entry("TypeScript", "tool", { aliases: ["TS"], eraMin: 2012 }),
  // Data engineering
  entry("ETL", "tool", { timeless: true }),
  entry("ELT", "tool", { eraMin: 2010 }),
  entry("dbt", "tool"),
  entry("Spark", "tool"),
  entry("PySpark", "tool"),
  entry("Kafka", "tool"),
  entry("Hadoop", "tool"),
  entry("Hive", "tool"),
  entry("SSIS", "tool"),
  entry("SSRS", "tool"),
  entry("SSAS", "tool"),
  entry("Informatica", "tool"),
  entry("DataStage", "tool"),
  entry("Talend", "tool"),
  // BI / analytics
  entry("Power BI", "tool", { aliases: ["PowerBI"] }),
  entry("Tableau", "tool"),
  entry("Looker", "tool"),
  entry("Qlik", "tool"),
  entry("Excel", "tool", { timeless: true }),
  entry("VBA", "tool", { timeless: true, eraMin: 1993 }),
  // Integration / APIs
  entry("REST", "tool", { eraMin: 2000 }),
  entry("SOAP", "tool", { eraMin: 1998 }),
  entry("OData", "tool", { aliases: ["ODATA"], eraMin: 2007 }),
  entry("IDoc", "tool", { aliases: ["IDOC"], eraMin: 1992 }),
  entry("BAPI", "tool", { eraMin: 1995 }),
  entry("GraphQL", "tool", { eraMin: 2015 }),
  entry("MuleSoft", "tool", { eraMin: 2006 }),
  entry("Boomi", "tool", { eraMin: 2012 }),
  entry("WebMethods", "tool", { eraMin: 1996 }),
  // ERP / modules — domain-specific (NOT timeless; eraMin = existed-by)
  entry("ERP", "tool", { timeless: true }),
  entry("CRM", "tool", { timeless: true }),
  entry("HCM", "tool", { timeless: true }),
  entry("SCM", "tool", { timeless: true }),
  entry("WMS", "tool", { eraMin: 1995 }),
  entry("TMS", "tool", { eraMin: 1995 }),
  entry("GL", "tool", { timeless: true }),
  entry("AP", "tool", { timeless: true }),
  entry("AR", "tool", { timeless: true }),
  entry("FA", "tool", { eraMin: 1990 }),
  entry("CO", "tool", { eraMin: 1992 }),
  entry("MM", "tool", { eraMin: 1992 }),
  entry("SD", "tool", { eraMin: 1992 }),
  entry("PP", "tool", { eraMin: 1992 }),
  entry("QM", "tool", { eraMin: 1992 }),
  entry("PM", "tool", { eraMin: 1992 }),
  entry("WM", "tool", { eraMin: 1995 }),
  entry("EWM", "tool", { eraMin: 2010 }),
  entry("TM", "tool", { eraMin: 2006 }),
  entry("MDG", "tool", { eraMin: 2012 }),
  entry("MDM", "tool", { eraMin: 2000 }),
  entry("BRIM", "tool", { eraMin: 2015 }),
  entry("FI-CA", "tool", { aliases: ["FICA"], eraMin: 2010 }),
  entry("FICO", "tool", { eraMin: 1992 }),
  entry("RTR", "tool", { eraMin: 2005 }),
  entry("OTC", "tool", { aliases: ["O2C"], timeless: true }),
  entry("PTP", "tool", { aliases: ["P2P"], timeless: true }),
  entry("RAR", "tool", { eraMin: 2016 }),
  entry("IBP", "tool", { eraMin: 2016 }),
  entry("BPC", "tool", { eraMin: 2007 }),
  entry("BW", "tool", { eraMin: 1998 }),
  entry("BW/4HANA", "tool", { aliases: ["BW4HANA"], eraMin: 2016 }),
  entry("SAC", "tool", { eraMin: 2018 }),
  entry("Fiori", "tool", { eraMin: 2013 }),
  entry("UI5", "tool", { eraMin: 2013 }),
  entry("ECC", "tool", { eraMin: 2004, eraMax: 2027 }),
  entry("S/4HANA", "tool", { aliases: ["S4HANA", "S4"], eraMin: 2015 }),
  entry("HANA", "tool", { eraMin: 2012 }),
  entry("ATTP", "tool", { eraMin: 2016 }),
  entry("EPCIS", "tool", { eraMin: 2014 }),
  entry("GTIN", "tool", { eraMin: 2000 }),
  entry("SSCC", "tool", { eraMin: 2000 }),
  entry("GTS", "tool", { eraMin: 2003 }),
  entry("Ariba", "tool", { eraMin: 1996 }),
  entry("Concur", "tool", { eraMin: 1993 }),
  entry("SuccessFactors", "tool", { aliases: ["SF"], eraMin: 2001 }),
  entry("Vertex", "tool", { eraMin: 1990 }),
  entry("Coupa", "tool", { eraMin: 2006 }),
  entry("OpenText", "tool", { eraMin: 1991 }),
  entry("VIM", "tool", { eraMin: 2005 }),
  entry("Salesforce", "tool", { eraMin: 1999 }),
  entry("Service Cloud", "tool", { eraMin: 2009 }),
  entry("Workday", "tool", { eraMin: 2005 }),
  entry("Oracle EBS", "tool", { aliases: ["EBS"], eraMin: 1987 }),
  entry("PeopleSoft", "tool", { eraMin: 1987 }),
  entry("NetSuite", "tool", { eraMin: 1998 }),
  entry("Dynamics 365", "tool", { aliases: ["D365"], eraMin: 2016 }),
  // Master data / quality
  entry("Master Data", "tool", { timeless: true }),
  entry("Data Quality", "tool", { timeless: true }),
  entry("Data Mapping", "tool", { timeless: true }),
  entry("Reconciliation", "tool", { timeless: true }),
  entry("Reporting", "tool", { timeless: true }),
  entry("Dashboards", "tool", { timeless: true }),
  entry("KPI Design", "tool", { timeless: true }),
  // Testing tools (product-ish)
  entry("Selenium", "tool"),
  entry("Postman", "tool"),
  entry("SoapUI", "tool"),
  entry("LoadRunner", "tool"),
  entry("JMeter", "tool"),
  // Security / identity products (auth protocols — not runtime platforms)
  entry("SSO", "tool"),
  entry("SAML", "tool"),
  entry("OAuth", "tool"),
  entry("LDAP", "tool"),
  entry("OpenID Connect", "tool", { aliases: ["OIDC"], eraMin: 2014 }),
  entry("JWT", "tool", { eraMin: 2012 }),
  // Extra system-agnostic delivery tools
  entry("C#", "tool", { aliases: ["CSharp"] }),
  entry("Go", "tool"),
  entry("Ruby", "tool"),
  entry("Perl", "tool"),
  entry("Shell", "tool"),
  entry("PowerShell", "tool"),
  entry("Bash", "tool"),
  entry("XML", "tool"),
  entry("JSON", "tool"),
  entry("YAML", "tool"),
  entry("Flat files", "tool"),
  entry("XSLT", "tool"),
  entry("Regex", "tool"),
  entry("API design", "tool"),
  entry("Microservices patterns", "tool", { eraMin: 2014 }),
  entry("Event streaming", "tool", { eraMin: 2014 }),
  entry("Batch jobs", "tool"),
  entry("Scheduled jobs", "tool"),
  entry("Workflow automation", "tool"),
  entry("RPA", "tool", { eraMin: 2015 }),
  entry("UiPath", "tool", { eraMin: 2015 }),
  entry("Blue Prism", "tool", { eraMin: 2014 }),
  entry("Automation Anywhere", "tool", { eraMin: 2014 }),
  entry("Crystal Reports", "tool"),
  entry("Business Objects", "tool", { aliases: ["BO", "SAP BO"] }),
  entry("Cognos", "tool"),
  entry("MicroStrategy", "tool"),
  entry("Access", "tool"),
  entry("Visio", "tool"),
  entry("Lucidchart", "tool"),
  entry("Draw.io", "tool"),
  entry("Figma", "tool", { eraMin: 2016 }),
  entry("Swagger", "tool", { eraMin: 2011 }),
  entry("OpenAPI", "tool", { eraMin: 2015 }),
  entry("Protobuf", "tool", { eraMin: 2012 }),
  entry("Avro", "tool", { eraMin: 2012 }),
  entry("Parquet", "tool", { eraMin: 2013 }),
  entry("Delta Lake", "tool", { eraMin: 2019 }),
  entry("Airflow DAGs", "tool", { eraMin: 2015 }),
  entry("NiFi", "tool", { eraMin: 2014 }),
  entry("Pentaho", "tool"),
  entry("Alteryx", "tool", { eraMin: 2012 }),
  entry("SAS", "tool"),
  entry("SPSS", "tool"),
  entry("Matlab", "tool"),
  entry("Anaplan", "tool", { eraMin: 2012 }),
  entry("Hyperion", "tool"),
  entry("Essbase", "tool"),
  entry("TM1", "tool"),
  entry("Planning Analytics", "tool", { eraMin: 2016 }),
  entry("Maximo", "tool"),
  entry("ServiceMax", "tool"),
  entry("Siebel", "tool"),
  entry("JD Edwards", "tool", { aliases: ["JDE"] }),
  entry("Baan", "tool"),
  entry("Infor", "tool"),
  entry("Epicor", "tool"),
  entry("Sage", "tool"),
  entry("QuickBooks", "tool"),
  entry("Xero", "tool"),
  entry("Stripe", "tool", { eraMin: 2012 }),
  entry("PayPal", "tool"),
  entry("Adyen", "tool", { eraMin: 2014 }),
  entry("Twilio", "tool", { eraMin: 2010 }),
  entry("SendGrid", "tool", { eraMin: 2012 }),
  entry("Elasticsearch", "tool", { eraMin: 2010 }),
  entry("Solr", "tool"),
  entry("Neo4j", "tool", { eraMin: 2010 }),
  entry("Cassandra", "tool", { eraMin: 2010 }),
  entry("DynamoDB patterns", "tool", { eraMin: 2012 }),
  entry("RabbitMQ", "tool"),
  entry("ActiveMQ", "tool"),
  entry("IBM MQ", "tool", { aliases: ["MQ Series"] }),
  entry("Tibco", "tool"),
  entry("WebSphere", "tool"),
  entry("WebLogic", "tool"),
  entry("Tomcat", "tool"),
  entry("Nginx", "tool"),
  entry("Apache", "tool"),
  entry("IIS", "tool"),
  entry("Mainframe", "tool"),
  entry("COBOL", "tool"),
  entry("JCL", "tool"),
  entry("CICS", "tool"),
  entry("DB2", "tool"),
  entry("IMS", "tool"),
  entry("VSAM", "tool"),
  entry("AS/400", "tool", { aliases: ["IBM i"] }),
  entry("RPG", "tool"),
  entry("EDI", "tool"),
  entry("X12", "tool"),
  entry("EDIFACT", "tool"),
  entry("HL7", "tool"),
  entry("FHIR", "tool", { eraMin: 2014 }),
  entry("DICOM", "tool"),
  entry("Barcode scanning", "tool"),
  entry("RFID", "tool"),
  entry("IoT gateways", "tool", { eraMin: 2014 }),
  entry("GIS", "tool"),
  entry("CAD", "tool"),
  entry("PLM", "tool"),
  entry("MES", "tool"),
  entry("SCADA", "tool"),
  entry("LIMS", "tool"),
  entry("QMS software", "tool"),
  entry("Documentum", "tool"),
  entry("SharePoint", "tool"),
  entry("Box", "tool", { eraMin: 2010 }),
  entry("Dropbox", "tool", { eraMin: 2010 }),
  entry("OneDrive", "tool", { eraMin: 2014 }),
  entry("Notion", "tool", { eraMin: 2018 }),
  entry("Asana", "tool", { eraMin: 2012 }),
  entry("Trello", "tool", { eraMin: 2011 }),
  entry("Monday.com", "tool", { eraMin: 2014 }),
  entry("Smartsheet", "tool"),
  entry("MS Project", "tool"),
  entry("Primavera", "tool"),
  entry("Clarity PPM", "tool"),
  entry("Service Catalog design", "tool"),
  entry("CMDB modeling", "tool"),
  entry("ITAM", "tool"),
  entry("Observability dashboards", "tool", { eraMin: 2016 }),
  entry("Prometheus metrics", "tool", { eraMin: 2015 }),
  entry("Grafana", "tool", { eraMin: 2014 }),
  entry("Splunk", "tool"),
  entry("ELK", "tool", { eraMin: 2012 }),
  entry("Datadog", "tool", { eraMin: 2012 }),
  entry("New Relic", "tool"),
  entry("AppDynamics", "tool"),
  entry("Dynatrace", "tool"),
  entry("PagerDuty", "tool", { eraMin: 2010 }),
  entry("Opsgenie", "tool", { eraMin: 2012 }),
  entry("Terraform modules", "tool", { eraMin: 2015 }),
  entry("Ansible", "tool", { eraMin: 2013 }),
  entry("Chef", "tool"),
  entry("Puppet", "tool"),
  entry("CloudFormation", "tool", { eraMin: 2011 }),
  entry("ARM templates", "tool", { eraMin: 2014 }),
  entry("Bicep", "tool", { eraMin: 2020 }),
  entry("Helm charts", "tool", { eraMin: 2016 }),
  entry("Argo CD", "tool", { eraMin: 2018 }),
  entry("GitHub Actions", "tool", { eraMin: 2019 }),
  entry("GitLab CI", "tool", { eraMin: 2015 }),
  entry("CircleCI", "tool", { eraMin: 2013 }),
  entry("TeamCity", "tool"),
  entry("Bamboo", "tool"),
  entry("Nexus", "tool"),
  entry("Artifactory", "tool"),
  entry("SonarQube", "tool"),
  entry("Checkmarx", "tool"),
  entry("Veracode", "tool"),
  entry("Snyk", "tool", { eraMin: 2015 }),
  entry("OWASP ZAP", "tool"),
  entry("Burp Suite", "tool"),
  entry("Wireshark", "tool"),
  entry("Fiddler", "tool"),
  entry("Charles Proxy", "tool"),
  entry("Insomnia", "tool", { eraMin: 2016 }),
  entry("Bruno", "tool", { eraMin: 2022 }),
  entry("Cypress", "tool", { eraMin: 2017 }),
  entry("Playwright", "tool", { eraMin: 2020 }),
  entry("Jest", "tool", { eraMin: 2014 }),
  entry("JUnit", "tool"),
  entry("TestNG", "tool"),
  entry("Cucumber", "tool"),
  entry("SpecFlow", "tool"),
  entry("Robot Framework", "tool"),
  entry("QTP/UFT", "tool", { aliases: ["UFT", "QTP"] }),
  entry("Tosca", "tool"),
  entry("Tricentis", "tool"),
  entry("ReadyAPI", "tool"),
  entry("SoapUI Pro", "tool"),
  entry("Gatling", "tool", { eraMin: 2012 }),
  entry("k6", "tool", { eraMin: 2017 }),
  entry("BlazeMeter", "tool"),
  entry("BrowserStack", "tool", { eraMin: 2012 }),
  entry("Sauce Labs", "tool"),
  entry("Appium", "tool", { eraMin: 2012 }),
  entry("Xamarin", "tool", { eraMin: 2013 }),
  entry("React Native", "tool", { eraMin: 2015 }),
  entry("Flutter", "tool", { eraMin: 2017 }),
  entry("React", "tool", { eraMin: 2013 }),
  entry("Angular", "tool", { eraMin: 2010 }),
  entry("Vue", "tool", { eraMin: 2014 }),
  entry("Node.js", "tool", { aliases: ["Node"], eraMin: 2010 }),
  entry("Express", "tool", { eraMin: 2010 }),
  entry("Spring Boot", "tool", { eraMin: 2014 }),
  entry(".NET", "tool", { aliases: ["dotnet"] }),
  entry(".NET Core", "tool", { eraMin: 2016 }),
  entry("Entity Framework", "tool"),
  entry("Hibernate", "tool"),
  entry("Django", "tool"),
  entry("Flask", "tool"),
  entry("FastAPI", "tool", { eraMin: 2019 }),
  entry("Rails", "tool"),
  entry("Laravel", "tool", { eraMin: 2011 }),
  entry("WordPress", "tool"),
  entry("Drupal", "tool"),
  entry("Sitecore", "tool"),
  entry("Adobe Experience Manager", "tool", { aliases: ["AEM"] }),
  entry("Contentful", "tool", { eraMin: 2013 }),
  entry("Shopify", "tool"),
  entry("Magento", "tool"),
  entry("Hybris", "tool"),
  entry("Commerce Cloud", "tool", { eraMin: 2016 }),
  entry("Marketo", "tool"),
  entry("HubSpot", "tool"),
  entry("Pardot", "tool"),
  entry("Eloqua", "tool"),
  entry("Segment", "tool", { eraMin: 2013 }),
  entry("mParticle", "tool", { eraMin: 2015 }),
  entry("Amplitude", "tool", { eraMin: 2012 }),
  entry("Mixpanel", "tool"),
  entry("Google Analytics", "tool"),
  entry("Adobe Analytics", "tool"),
  entry("Optimizely", "tool"),
  entry("LaunchDarkly", "tool", { eraMin: 2014 }),
  entry("Feature flags", "tool", { eraMin: 2014 }),
  entry("A/B testing harness", "tool"),
  entry("Tax engines", "tool"),
  entry("Avalara", "tool"),
  entry("Payment gateways", "tool"),
  entry("Treasury systems", "tool"),
  entry("Bank feeds", "tool"),
  entry("Lockbox", "tool"),
  entry("Positive pay", "tool"),
  entry("Wire systems", "tool"),
  entry("ACH", "tool"),
  entry("SEPA", "tool"),
  entry("SWIFT messaging", "tool"),
  entry("Core banking", "tool"),
  entry("Claims systems", "tool"),
  entry("Policy admin", "tool"),
  entry("Underwriting engines", "tool"),
  entry("Rating engines", "tool"),
  entry("Reservations systems", "tool"),
  entry("POS", "tool"),
  entry("E-commerce catalog", "tool"),
  entry("Inventory engines", "tool"),
  entry("Pricing engines", "tool"),
  entry("Promotion engines", "tool"),
  entry("Loyalty platforms", "tool"),
  entry("OMS", "tool"),
  entry("DOM", "tool"),
  entry("Yard management", "tool"),
  entry("Fleet management", "tool"),
  entry("Route optimization", "tool"),
  entry("Demand planning", "tool"),
  entry("Supply planning", "tool"),
  entry("MRP", "tool"),
  entry("Capacity planning", "tool"),
  entry("Shop floor control", "tool"),
  entry("Quality inspection", "tool"),
  entry("Calibration systems", "tool"),
  entry("EHS systems", "tool"),
  entry("Sustainability reporting tools", "tool", { eraMin: 2018 }),
  entry("Carbon accounting", "tool", { eraMin: 2018 }),
  entry("Contract lifecycle", "tool", { aliases: ["CLM"] }),
  entry("eSignature", "tool", { eraMin: 2010 }),
  entry("DocuSign", "tool", { eraMin: 2010 }),
  entry("Adobe Sign", "tool", { eraMin: 2011 }),
  entry("Legal hold tools", "tool"),
  entry("eDiscovery", "tool"),
  entry("Records management", "tool"),
  entry("Archive systems", "tool"),
  entry("Data lake design", "tool", { eraMin: 2014 }),
  entry("Data mesh patterns", "tool", { eraMin: 2019 }),
  entry("Data contracts", "tool", { eraMin: 2018 }),
  entry("Feature stores", "tool", { eraMin: 2018 }),
  entry("ML pipelines", "tool", { eraMin: 2016 }),
  entry("Model monitoring", "tool", { eraMin: 2018 }),
  entry("Vector search", "tool", { eraMin: 2021 }),
  entry("LLM orchestration", "tool", { eraMin: 2023 }),
  entry("Prompt evaluation", "tool", { eraMin: 2023 }),
  entry("RAG patterns", "tool", { eraMin: 2023 }),
];

/**
 * PLATFORMS — runtime / cloud / collab / ALM (Environment lane only).
 * Disjoint from tools list.
 */
const PLATFORMS: CatalogEntry[] = [
  entry("Azure", "platform", { eraMin: 2012 }),
  entry("AWS", "platform", { eraMin: 2008 }),
  entry("GCP", "platform", { eraMin: 2012 }),
  entry("Public Cloud", "platform", { eraMin: 2014 }),
  entry("Private Cloud", "platform", { eraMin: 2010 }),
  entry("Hybrid Cloud", "platform", { eraMin: 2014 }),
  entry("On-premise", "platform", { aliases: ["On Premise", "On Prem"] }),
  entry("Windows Server", "platform"),
  entry("Linux", "platform"),
  entry("SQL Server", "platform"),
  entry("Oracle DB", "platform", { aliases: ["Oracle Database"] }),
  entry("PostgreSQL", "platform", { aliases: ["Postgres"] }),
  entry("MySQL", "platform"),
  entry("MongoDB", "platform"),
  entry("Redis", "platform"),
  entry("Snowflake", "platform", { eraMin: 2015 }),
  entry("Redshift", "platform", { eraMin: 2013 }),
  entry("BigQuery", "platform", { eraMin: 2012 }),
  entry("Databricks", "platform", { eraMin: 2015 }),
  entry("Synapse", "platform", { aliases: ["Azure Synapse"], eraMin: 2019 }),
  entry("Data Factory", "platform", { aliases: ["ADF"], eraMin: 2015 }),
  entry("Logic Apps", "platform", { eraMin: 2016 }),
  entry("Event Hub", "platform", { eraMin: 2015 }),
  entry("Cosmos DB", "platform", { eraMin: 2017 }),
  entry("Docker", "platform", { eraMin: 2014 }),
  entry("Kubernetes", "platform", { aliases: ["K8s"], eraMin: 2016 }),
  entry("Terraform", "platform", { eraMin: 2015 }),
  entry("BTP", "platform", { eraMin: 2019 }),
  entry("CPI", "platform", { aliases: ["SAP CPI"], eraMin: 2017 }),
  entry("PI/PO", "platform", { aliases: ["PI", "PO", "SAP PI"] }),
  entry("SolMan", "platform", { aliases: ["Solution Manager"] }),
  entry("ALM", "platform"),
  entry("HP ALM", "platform", { aliases: ["QC", "Quality Center"] }),
  entry("Jira", "platform", { aliases: ["JIRA"] }),
  entry("Confluence", "platform"),
  entry("ServiceNow", "platform", { aliases: ["Service Now", "SNOW"] }),
  entry("Azure DevOps", "platform", { aliases: ["ADO", "TFS"], eraMin: 2018 }),
  entry("GitHub", "platform"),
  entry("GitLab", "platform"),
  entry("Bitbucket", "platform"),
  entry("Git", "platform"),
  entry("Jenkins", "platform"),
  entry("Client site", "platform"),
  entry("Remote delivery", "platform", { eraMin: 2012 }),
  entry("Shared services hub", "platform"),
  entry("Data center", "platform"),
  entry("VDI", "platform"),
  entry("Citrix", "platform"),
  entry("VPN", "platform"),
  entry("Active-active DR", "platform", { eraMin: 2014 }),
  entry("Staging landscape", "platform"),
  entry("Sandbox", "platform"),
  entry("QA landscape", "platform"),
  entry("Prod landscape", "platform"),
  entry("Transport landscape", "platform"),
  entry("RISE", "platform", { eraMin: 2021 }),
  entry("Datasphere", "platform", { eraMin: 2022 }),
  // Identity / endpoint as environment (not delivery tools)
  entry("Active Directory", "platform", { aliases: ["AD"] }),
  entry("Azure AD", "platform", { aliases: ["Entra ID", "AAD"], eraMin: 2013 }),
  entry("Okta", "platform", { eraMin: 2010 }),
  entry("PingFederate", "platform"),
  entry("Duo", "platform", { eraMin: 2012 }),
  entry("CyberArk", "platform"),
  entry("SailPoint", "platform"),
  entry("Saviynt", "platform", { eraMin: 2015 }),
  // More landscapes / collab / infra
  entry("Mainframe LPAR", "platform"),
  entry("AS/400 host", "platform"),
  entry("VMware", "platform"),
  entry("Hyper-V", "platform"),
  entry("OpenShift", "platform", { eraMin: 2011 }),
  entry("EKS", "platform", { eraMin: 2018 }),
  entry("AKS", "platform", { eraMin: 2018 }),
  entry("GKE", "platform", { eraMin: 2015 }),
  entry("Cloud Foundry", "platform", { eraMin: 2011 }),
  entry("Heroku", "platform", { eraMin: 2009 }),
  entry("Cloudflare", "platform", { eraMin: 2010 }),
  entry("Akamai", "platform"),
  entry("Fastly", "platform", { eraMin: 2011 }),
  entry("CDN edge", "platform"),
  entry("WAF tier", "platform"),
  entry("API gateway", "platform", { eraMin: 2012 }),
  entry("Kong", "platform", { eraMin: 2015 }),
  entry("Apigee", "platform", { eraMin: 2012 }),
  entry("Mule runtime", "platform", { eraMin: 2012 }),
  entry("Integration suite", "platform", { eraMin: 2018 }),
  entry("iPaaS tenant", "platform", { eraMin: 2014 }),
  entry("Multi-tenant SaaS", "platform", { eraMin: 2012 }),
  entry("Single-tenant SaaS", "platform", { eraMin: 2012 }),
  entry("Colocation", "platform"),
  entry("Edge sites", "platform", { eraMin: 2016 }),
  entry("DR site", "platform"),
  entry("Hot standby", "platform"),
  entry("Cold standby", "platform"),
  entry("Blue-green slots", "platform", { eraMin: 2012 }),
  entry("Canary slots", "platform", { eraMin: 2014 }),
  entry("Feature environments", "platform", { eraMin: 2015 }),
  entry("Ephemeral envs", "platform", { eraMin: 2018 }),
  entry("Dev landscape", "platform"),
  entry("SIT landscape", "platform"),
  entry("UAT landscape", "platform"),
  entry("Pre-prod landscape", "platform"),
  entry("Training landscape", "platform"),
  entry("Sandbox tenant", "platform"),
  entry("Production tenant", "platform"),
  entry("Partner portal", "platform"),
  entry("Customer portal", "platform"),
  entry("Mobile backend", "platform", { eraMin: 2012 }),
  entry("Offline-first field", "platform"),
  entry("Warehouse RF network", "platform"),
  entry("Shop floor network", "platform"),
  entry("OT network", "platform"),
  entry("Air-gapped network", "platform"),
  entry("Zero-trust network", "platform", { eraMin: 2018 }),
  entry("SD-WAN", "platform", { eraMin: 2014 }),
  entry("MPLS", "platform"),
  entry("Teams", "platform", { eraMin: 2017 }),
  entry("Slack", "platform", { eraMin: 2013 }),
  entry("Zoom", "platform", { eraMin: 2013 }),
  entry("Webex", "platform"),
  entry("Miro", "platform", { eraMin: 2015 }),
  entry("Mural", "platform", { eraMin: 2014 }),
  entry("FigJam", "platform", { eraMin: 2021 }),
  entry("Monday boards", "platform", { eraMin: 2014 }),
  entry("Smartsheet workspace", "platform"),
  entry("ServiceNow instance", "platform"),
  entry("Jira Cloud", "platform", { eraMin: 2012 }),
  entry("Jira Data Center", "platform"),
  entry("Confluence Cloud", "platform", { eraMin: 2012 }),
  entry("SharePoint Online", "platform", { eraMin: 2013 }),
  entry("SharePoint on-prem", "platform"),
  entry("Exchange Online", "platform", { eraMin: 2013 }),
  entry("Outlook", "platform"),
  entry("Power Platform", "platform", { eraMin: 2018 }),
  entry("Power Apps environment", "platform", { eraMin: 2016 }),
  entry("Dataverse environment", "platform", { eraMin: 2018 }),
  entry("Salesforce org", "platform"),
  entry("Salesforce sandbox", "platform"),
  entry("Workday tenant", "platform", { eraMin: 2010 }),
  entry("SuccessFactors instance", "platform"),
  entry("Oracle Cloud", "platform", { eraMin: 2016 }),
  entry("OCI", "platform", { eraMin: 2016 }),
  entry("IBM Cloud", "platform", { eraMin: 2013 }),
  entry("Alibaba Cloud", "platform", { eraMin: 2015 }),
  entry("DigitalOcean", "platform", { eraMin: 2011 }),
  entry("Linode", "platform"),
  entry("Bare metal", "platform"),
  entry("Raspberry Pi lab", "platform", { eraMin: 2012 }),
  entry("Laptop image fleet", "platform"),
  entry("MDM-enrolled devices", "platform", { eraMin: 2012 }),
  entry("Intune", "platform", { eraMin: 2014 }),
  entry("SCCM", "platform"),
  entry("Jamf", "platform"),
  entry("Print servers", "platform"),
  entry("File servers", "platform"),
  entry("NAS", "platform"),
  entry("SAN", "platform"),
  entry("Object storage", "platform", { eraMin: 2010 }),
  entry("S3 buckets", "platform", { eraMin: 2008 }),
  entry("Blob storage", "platform", { eraMin: 2012 }),
  entry("GCS buckets", "platform", { eraMin: 2010 }),
  entry("Tape archive", "platform"),
  entry("Backup vault", "platform"),
  entry("SIEM console", "platform"),
  entry("SOC workspace", "platform"),
  entry("NOC", "platform"),
  entry("Command center", "platform"),
  entry("War room", "platform"),
  entry("Hypercare bridge", "platform"),
  entry("Vendor secure room", "platform"),
  entry("Clean room", "platform"),
];

/**
 * PROCESSES — delivery methods (never duplicate tool/platform terms).
 */
const PROCESSES: CatalogEntry[] = [
  entry("SDLC", "process"),
  entry("Agile", "process"),
  entry("Scrum", "process"),
  entry("Kanban", "process"),
  entry("Waterfall", "process"),
  entry("Hybrid delivery", "process"),
  entry("SAFe", "process", { eraMin: 2014 }),
  entry("DevOps", "process", { eraMin: 2012 }),
  entry("CI/CD", "process", { eraMin: 2012 }),
  entry("ITIL", "process"),
  entry("ITSM", "process"),
  entry("Discovery workshops", "process"),
  entry("Requirements gathering", "process"),
  entry("Gap analysis", "process"),
  entry("Fit-gap", "process"),
  entry("Blueprinting", "process"),
  entry("Solution design", "process"),
  entry("Configuration", "process"),
  entry("Customization", "process"),
  entry("Unit testing", "process"),
  entry("SIT", "process"),
  entry("UAT", "process"),
  entry("Regression testing", "process"),
  entry("Performance testing", "process"),
  entry("Security testing", "process"),
  entry("Defect triage", "process"),
  entry("Root cause analysis", "process"),
  entry("Cutover planning", "process"),
  entry("Dress rehearsal", "process"),
  entry("Go-live", "process"),
  entry("Hypercare", "process"),
  entry("Knowledge transfer", "process"),
  entry("Runbook authoring", "process"),
  entry("Change management", "process"),
  entry("CAB", "process"),
  entry("Release management", "process"),
  entry("Incident management", "process"),
  entry("Problem management", "process"),
  entry("RACI", "process"),
  entry("RAID log", "process"),
  entry("Steering reporting", "process"),
  entry("Backlog refinement", "process"),
  entry("Sprint planning", "process"),
  entry("Daily stand-up", "process"),
  entry("Retrospective", "process"),
  entry("Data migration", "process"),
  entry("Mock conversion", "process"),
  entry("Reconciliation cycles", "process"),
  entry("Interface mapping", "process"),
  entry("Master data cleanup", "process"),
  entry("Training delivery", "process"),
  entry("Train-the-trainer", "process"),
  entry("Floor support", "process"),
  entry("Adoption tracking", "process"),
  entry("Lessons learned", "process"),
  entry("Continuous improvement", "process"),
  entry("Value stream mapping", "process"),
  entry("Process mining", "process", { eraMin: 2016 }),
  // Extra agnostic delivery processes
  entry("Stakeholder management", "process"),
  entry("Executive briefing", "process"),
  entry("Working group facilitation", "process"),
  entry("Decision log hygiene", "process"),
  entry("Scope baselining", "process"),
  entry("Change request process", "process"),
  entry("Impact assessment", "process"),
  entry("Dependency mapping", "process"),
  entry("Capacity planning sessions", "process"),
  entry("Estimation workshops", "process"),
  entry("Story mapping", "process", { eraMin: 2012 }),
  entry("Event storming", "process", { eraMin: 2013 }),
  entry("Domain modeling", "process"),
  entry("Threat modeling", "process"),
  entry("Architecture review board", "process"),
  entry("Design authority", "process"),
  entry("Code review", "process"),
  entry("Pair programming", "process"),
  entry("Mob programming", "process", { eraMin: 2014 }),
  entry("Trunk-based development", "process", { eraMin: 2014 }),
  entry("Gitflow", "process", { eraMin: 2010 }),
  entry("Feature branching", "process"),
  entry("Pull request workflow", "process", { eraMin: 2010 }),
  entry("Definition of ready", "process"),
  entry("Definition of done", "process"),
  entry("Acceptance criteria writing", "process"),
  entry("Three amigos", "process"),
  entry("Shift-left testing", "process", { eraMin: 2012 }),
  entry("Shift-right testing", "process", { eraMin: 2016 }),
  entry("Chaos testing", "process", { eraMin: 2016 }),
  entry("Game days", "process", { eraMin: 2014 }),
  entry("Tabletop exercises", "process"),
  entry("Disaster recovery drill", "process"),
  entry("Business continuity drill", "process"),
  entry("Penetration test coordination", "process"),
  entry("Vulnerability remediation", "process"),
  entry("Patch management", "process"),
  entry("Capacity test", "process"),
  entry("Soak test", "process"),
  entry("Failover test", "process"),
  entry("Rollback drill", "process"),
  entry("Feature toggle rollout", "process", { eraMin: 2014 }),
  entry("Canary release", "process", { eraMin: 2014 }),
  entry("Blue-green release", "process", { eraMin: 2012 }),
  entry("Dark launch", "process", { eraMin: 2014 }),
  entry("Progressive delivery", "process", { eraMin: 2018 }),
  entry("Site reliability practices", "process", { eraMin: 2016 }),
  entry("Error budget review", "process", { eraMin: 2016 }),
  entry("Postmortem", "process"),
  entry("Blameless review", "process", { eraMin: 2012 }),
  entry("Ops handover", "process"),
  entry("BAU transition", "process"),
  entry("Warranty support", "process"),
  entry("Ticket triage", "process"),
  entry("SLA management", "process"),
  entry("OLA management", "process"),
  entry("Vendor management", "process"),
  entry("SOW tracking", "process"),
  entry("Invoice milestone review", "process"),
  entry("Time tracking discipline", "process"),
  entry("Resource leveling", "process"),
  entry("Cross-training", "process"),
  entry("Shadow support", "process"),
  entry("Floor walking", "process"),
  entry("War-room facilitation", "process"),
  entry("Command cadence", "process"),
  entry("Daily defect burn-down", "process"),
  entry("Quality gate review", "process"),
  entry("Exit criteria review", "process"),
  entry("Entry criteria review", "process"),
  entry("Readiness checklist", "process"),
  entry("Go/no-go facilitation", "process"),
  entry("Cutover command", "process"),
  entry("Mock cutover", "process"),
  entry("Data dress rehearsal", "process"),
  entry("Interface partner call", "process"),
  entry("Mapping workshop", "process"),
  entry("Reconciliation sign-off", "process"),
  entry("Control walkthrough", "process"),
  entry("Audit support", "process"),
  entry("Evidence collection", "process"),
  entry("Policy exception process", "process"),
  entry("Risk acceptance process", "process"),
  entry("Privacy impact assessment", "process", { eraMin: 2016 }),
  entry("DPIA", "process", { eraMin: 2018 }),
  entry("Data classification exercise", "process"),
  entry("Retention schedule review", "process"),
  entry("Access recertification", "process"),
  entry("Role mining", "process"),
  entry("SoD conflict resolution", "process"),
  entry("Segregation design", "process"),
  entry("Key user enablement", "process"),
  entry("Super-user program", "process"),
  entry("Communications plan", "process"),
  entry("Resistance management", "process"),
  entry("Adoption measurement", "process"),
  entry("Benefits tracking", "process"),
  entry("Value realization", "process"),
  entry("OKR alignment", "process", { eraMin: 2014 }),
  entry("KPI baselining", "process"),
  entry("Continuous discovery", "process", { eraMin: 2016 }),
  entry("Customer journey mapping", "process"),
  entry("Service blueprinting", "process"),
  entry("Persona workshops", "process"),
  entry("Usability testing", "process"),
  entry("Accessibility review", "process"),
  entry("Localization testing", "process"),
  entry("Multi-language UAT", "process"),
  entry("Parallel run", "process"),
  entry("Piloted cutover", "process"),
  entry("Big-bang cutover", "process"),
  entry("Phased rollout", "process"),
  entry("Pilot cohort", "process"),
  entry("Wave planning", "process"),
  entry("Country rollout", "process"),
  entry("Plant rollout", "process"),
  entry("Brand rollout", "process"),
];

/**
 * COMPLIANCE — frameworks / control programs (not tools, not regs).
 */
const COMPLIANCE: CatalogEntry[] = [
  entry("SOX", "compliance", { aliases: ["Sarbanes-Oxley"] }),
  entry("SOC 1", "compliance"),
  entry("SOC 2", "compliance", { aliases: ["SOC2"] }),
  entry("ISO 27001", "compliance"),
  entry("ISO 9001", "compliance"),
  entry("NIST", "compliance"),
  entry("COBIT", "compliance"),
  entry("ITGC", "compliance"),
  entry("SoD", "compliance", { aliases: ["Segregation of Duties"] }),
  entry("Access controls", "compliance"),
  entry("Least privilege", "compliance"),
  entry("Audit trail", "compliance"),
  entry("Internal audit", "compliance"),
  entry("External audit", "compliance"),
  entry("Control testing", "compliance"),
  entry("Evidence packs", "compliance"),
  entry("Policy alignment", "compliance"),
  entry("Risk assessment", "compliance"),
  entry("Vendor risk", "compliance"),
  entry("Data retention", "compliance"),
  entry("Privacy by design", "compliance"),
  entry("Change control", "compliance"),
  entry("CAB approval", "compliance"),
  entry("GxP", "compliance"),
  entry("CSV", "compliance", { aliases: ["Computer System Validation"] }),
  entry("21 CFR Part 11", "compliance", { aliases: ["Part 11"] }),
  entry("Data integrity ALCOA+", "compliance", { aliases: ["ALCOA"] }),
  entry("Quality management system", "compliance", { aliases: ["QMS"] }),
  entry("Business continuity", "compliance"),
  entry("DR testing", "compliance"),
  entry("Penetration test findings", "compliance"),
  entry("Vulnerability management", "compliance"),
  entry("Encryption standards", "compliance"),
  entry("Key management", "compliance"),
  // Extra agnostic control programs
  entry("ISO 27701", "compliance", { eraMin: 2019 }),
  entry("ISO 22301", "compliance"),
  entry("ISO 20000", "compliance"),
  entry("ISO 13485", "compliance"),
  entry("ISO 14001", "compliance"),
  entry("ISO 45001", "compliance"),
  entry("CMMI", "compliance"),
  entry("ITIL alignment", "compliance"),
  entry("CIS Controls", "compliance"),
  entry("CSA CCM", "compliance"),
  entry("HITRUST", "compliance"),
  entry("PCI SAQ", "compliance"),
  entry("PCI ROC", "compliance"),
  entry("FedRAMP Moderate", "compliance", { eraMin: 2012 }),
  entry("StateRAMP", "compliance", { eraMin: 2020 }),
  entry("IRAP", "compliance"),
  entry("ENS", "compliance"),
  entry("Cyber Essentials", "compliance"),
  entry("TISAX", "compliance"),
  entry("SOC 3", "compliance"),
  entry("ISAE 3402", "compliance"),
  entry("SSAE 18", "compliance"),
  entry("AT-C 205", "compliance"),
  entry("Model audit rule", "compliance"),
  entry("Internal control framework", "compliance"),
  entry("Entity-level controls", "compliance"),
  entry("Process-level controls", "compliance"),
  entry("Application controls", "compliance"),
  entry("Interface controls", "compliance"),
  entry("Job monitoring controls", "compliance"),
  entry("Reconciliations controls", "compliance"),
  entry("Manual compensating controls", "compliance"),
  entry("Automated controls", "compliance"),
  entry("Continuous controls monitoring", "compliance", { eraMin: 2014 }),
  entry("GRC program", "compliance"),
  entry("Policy management", "compliance"),
  entry("Exception management", "compliance"),
  entry("Issue management", "compliance"),
  entry("Remediation tracking", "compliance"),
  entry("Third-party risk management", "compliance"),
  entry("Fourth-party risk", "compliance", { eraMin: 2016 }),
  entry("Supply chain security", "compliance", { eraMin: 2018 }),
  entry("SBOM discipline", "compliance", { eraMin: 2021 }),
  entry("Secure SDLC", "compliance", { eraMin: 2012 }),
  entry("Threat intel integration", "compliance", { eraMin: 2014 }),
  entry("Security awareness", "compliance"),
  entry("Phishing simulations", "compliance", { eraMin: 2012 }),
  entry("Privileged access management", "compliance"),
  entry("Just-in-time access", "compliance", { eraMin: 2016 }),
  entry("Passwordless program", "compliance", { eraMin: 2018 }),
  entry("MFA enforcement", "compliance", { eraMin: 2012 }),
  entry("Session management standards", "compliance"),
  entry("Logging standards", "compliance"),
  entry("Retention standards", "compliance"),
  entry("Backup standards", "compliance"),
  entry("DR RTO/RPO targets", "compliance"),
  entry("BCP exercise evidence", "compliance"),
  entry("Privacy program", "compliance"),
  entry("Data subject request process", "compliance", { eraMin: 2018 }),
  entry("Consent management", "compliance", { eraMin: 2016 }),
  entry("Cookie compliance program", "compliance", { eraMin: 2016 }),
  entry("Cross-border transfer controls", "compliance", { eraMin: 2018 }),
  entry("SCC program", "compliance", { eraMin: 2021 }),
  entry("DPA inventory", "compliance", { eraMin: 2018 }),
  entry("RoPA", "compliance", { eraMin: 2018 }),
  entry("Data minimization", "compliance"),
  entry("Purpose limitation", "compliance"),
  entry("Ethics review board", "compliance", { eraMin: 2018 }),
  entry("Responsible AI program", "compliance", { eraMin: 2020 }),
  entry("Model risk management", "compliance", { eraMin: 2014 }),
  entry("Validation master plan", "compliance"),
  entry("IQ/OQ/PQ", "compliance"),
  entry("Change control board", "compliance"),
  entry("Deviation management", "compliance"),
  entry("CAPA", "compliance"),
  entry("Complaint handling", "compliance"),
  entry("Pharmacovigilance alignment", "compliance"),
  entry("Labeling controls", "compliance"),
  entry("Serialization readiness", "compliance", { eraMin: 2015 }),
  entry("Trade compliance program", "compliance"),
  entry("Sanctions screening program", "compliance"),
  entry("Anti-bribery program", "compliance"),
  entry("Whistleblower program", "compliance"),
  entry("Records retention schedule", "compliance"),
  entry("Legal hold program", "compliance"),
  entry("eDiscovery readiness", "compliance"),
];

/**
 * REGULATIONS — legal / industry rules (disjoint from compliance frameworks).
 */
const REGULATIONS: CatalogEntry[] = [
  entry("GDPR", "regulation"),
  entry("CCPA", "regulation"),
  entry("CPRA", "regulation", { eraMin: 2020 }),
  entry("HIPAA", "regulation"),
  entry("HITECH", "regulation"),
  entry("PCI-DSS", "regulation", { aliases: ["PCI"] }),
  entry("GLBA", "regulation"),
  entry("Basel III", "regulation"),
  entry("MiFID II", "regulation", { eraMin: 2018 }),
  entry("Dodd-Frank", "regulation"),
  entry("IFRS 15", "regulation", { eraMin: 2018 }),
  entry("IFRS 16", "regulation", { eraMin: 2019 }),
  entry("ASC 606", "regulation", { eraMin: 2018 }),
  entry("ASC 842", "regulation", { eraMin: 2019 }),
  entry("FDA", "regulation"),
  entry("DSCSA", "regulation", { eraMin: 2013 }),
  entry("FMD", "regulation", { eraMin: 2019 }),
  entry("EU MDR", "regulation", { eraMin: 2021 }),
  entry("FSMA", "regulation"),
  entry("DEA", "regulation"),
  entry("EMA", "regulation"),
  entry("GS1 standards", "regulation", { aliases: ["GS1"] }),
  entry("ePedigree", "regulation"),
  entry("Privacy Shield successor", "regulation", { eraMin: 2023 }),
  entry("Schrems II", "regulation", { eraMin: 2020 }),
  entry("TCPA", "regulation"),
  entry("CAN-SPAM", "regulation"),
  entry("COPPA", "regulation"),
  entry("FERPA", "regulation"),
  entry("FedRAMP", "regulation"),
  entry("State privacy acts", "regulation", { eraMin: 2020 }),
  entry("Export control", "regulation"),
  entry("OFAC screening", "regulation"),
  entry("AML", "regulation"),
  entry("KYC", "regulation"),
  // Extra agnostic / multi-industry regulations
  entry("UK GDPR", "regulation", { eraMin: 2021 }),
  entry("LGPD", "regulation", { eraMin: 2020 }),
  entry("PIPEDA", "regulation"),
  entry("PDPA", "regulation"),
  entry("POPIA", "regulation", { eraMin: 2020 }),
  entry("APPI", "regulation"),
  entry("PIPA", "regulation"),
  entry("PDPL", "regulation"),
  entry("ePrivacy", "regulation"),
  entry("NIS2", "regulation", { eraMin: 2023 }),
  entry("DORA", "regulation", { eraMin: 2023 }),
  entry("CRA", "regulation", { eraMin: 2024 }),
  entry("AI Act", "regulation", { eraMin: 2024 }),
  entry("DSA", "regulation", { eraMin: 2023 }),
  entry("DMA", "regulation", { eraMin: 2023 }),
  entry("CSA", "regulation", { eraMin: 2020 }),
  entry("CCPA/CPRA updates", "regulation", { eraMin: 2020 }),
  entry("VCDPA", "regulation", { eraMin: 2023 }),
  entry("CPA Colorado", "regulation", { eraMin: 2023 }),
  entry("CTDPA", "regulation", { eraMin: 2023 }),
  entry("UCPA", "regulation", { eraMin: 2023 }),
  entry("BIPA", "regulation"),
  entry("TCPA consent", "regulation"),
  entry("CAN-SPAM commercial", "regulation"),
  entry("CASL", "regulation"),
  entry("FTC Act Section 5", "regulation"),
  entry("COPPA parental", "regulation"),
  entry("GLBA Safeguards", "regulation"),
  entry("FCRA", "regulation"),
  entry("ECOA", "regulation"),
  entry("TILA", "regulation"),
  entry("RESPA", "regulation"),
  entry("HMDA", "regulation"),
  entry("BSA", "regulation"),
  entry("USA PATRIOT Act", "regulation"),
  entry("OFAC SDN", "regulation"),
  entry("EAR", "regulation"),
  entry("ITAR", "regulation"),
  entry("CFIUS", "regulation"),
  entry("Sanctions regimes", "regulation"),
  entry("Anti-money laundering directives", "regulation"),
  entry("PSD2", "regulation", { eraMin: 2018 }),
  entry("Open Banking rules", "regulation", { eraMin: 2018 }),
  entry("EMIR", "regulation"),
  entry("SFTR", "regulation", { eraMin: 2020 }),
  entry("MAR", "regulation"),
  entry("CFTC rules", "regulation"),
  entry("SEC Reg S-P", "regulation"),
  entry("SEC cybersecurity rules", "regulation", { eraMin: 2023 }),
  entry("FINRA rules", "regulation"),
  entry("NAIC model laws", "regulation"),
  entry("Solvency II", "regulation"),
  entry("IFRS 17", "regulation", { eraMin: 2023 }),
  entry("IFRS 9", "regulation", { eraMin: 2018 }),
  entry("CECL", "regulation", { eraMin: 2020 }),
  entry("Leases ASC 842", "regulation", { eraMin: 2019 }),
  entry("Revenue ASC 606", "regulation", { eraMin: 2018 }),
  entry("SOX 404", "regulation"),
  entry("J-SOX", "regulation"),
  entry("Bill 198", "regulation"),
  entry("CLIA", "regulation"),
  entry("CAP", "regulation"),
  entry("FDA 21 CFR 820", "regulation"),
  entry("FDA 21 CFR 211", "regulation"),
  entry("EU GMP Annex 11", "regulation"),
  entry("GAMP 5", "regulation"),
  entry("ICH guidelines", "regulation"),
  entry("Pharmacopeia standards", "regulation"),
  entry("DSCSA 2023 requirements", "regulation", { eraMin: 2023 }),
  entry("EU FMD safety features", "regulation", { eraMin: 2019 }),
  entry("UDI", "regulation", { eraMin: 2015 }),
  entry("MDR/IVDR", "regulation", { eraMin: 2021 }),
  entry("REACH", "regulation"),
  entry("RoHS", "regulation"),
  entry("WEEE", "regulation"),
  entry("Conflict minerals", "regulation"),
  entry("Modern Slavery Act", "regulation"),
  entry("Uyghur Forced Labor Act", "regulation", { eraMin: 2022 }),
  entry("CSRD", "regulation", { eraMin: 2023 }),
  entry("SFDR", "regulation", { eraMin: 2021 }),
  entry("TCFD", "regulation", { eraMin: 2017 }),
  entry("CDP disclosures", "regulation"),
  entry("OSHA", "regulation"),
  entry("EPA rules", "regulation"),
  entry("DOT hazmat", "regulation"),
  entry("IATA dangerous goods", "regulation"),
  entry("IMO codes", "regulation"),
  entry("FAA", "regulation"),
  entry("EASA", "regulation"),
  entry("NERC CIP", "regulation"),
  entry("TSA security directives", "regulation", { eraMin: 2021 }),
  entry("CISA directives", "regulation", { eraMin: 2021 }),
  entry("State breach notification laws", "regulation"),
  entry("NYDFS 500", "regulation", { eraMin: 2017 }),
  entry("MAS TRM", "regulation"),
  entry("APRA CPS 234", "regulation"),
  entry("OSFI guidelines", "regulation"),
  entry("BaFin requirements", "regulation"),
  entry("FCA rules", "regulation"),
  entry("PRA rules", "regulation"),
  entry("EBA guidelines", "regulation"),
  entry("ESMA guidelines", "regulation"),
  entry("Workers rights statutes", "regulation"),
  entry("Equal employment rules", "regulation"),
  entry("Wage and hour rules", "regulation"),
  entry("Whistleblower protections", "regulation"),
  entry("Public records laws", "regulation"),
  entry("FOIA", "regulation"),
  entry("Sunshine laws", "regulation"),
];

/**
 * TIMELESS / ERA-AGNOSTIC catalog — safe for 1995–present, any domain
 * (SAP, Oracle, Workday, Java, Data Eng, BA). Prefer these for early careers
 * and as bulk Technical Skills (40–50 items).
 * No eraMin = available any era.
 */
const TIMELESS_TOOLS: CatalogEntry[] = [
  tEntry("MS Office", "tool", { aliases: ["Microsoft Office"] }),
  tEntry("Word", "tool", { aliases: ["MS Word"] }),
  tEntry("PowerPoint", "tool", { aliases: ["MS PowerPoint", "PPT"] }),
  tEntry("Outlook", "tool"),
  tEntry("Access DB", "tool", { aliases: ["MS Access DB"] }),
  tEntry("Project plans", "tool"),
  tEntry("Requirements docs", "tool"),
  tEntry("Functional specs", "tool"),
  tEntry("Technical specs", "tool"),
  tEntry("Test cases", "tool"),
  tEntry("Test scripts", "tool"),
  tEntry("Use cases", "tool"),
  tEntry("User stories", "tool"),
  tEntry("Process flows", "tool"),
  tEntry("Flowcharts", "tool"),
  tEntry("Wireframes", "tool"),
  tEntry("Mockups", "tool"),
  tEntry("Traceability matrix", "tool"),
  tEntry("RTM", "tool"),
  tEntry("BRD", "tool"),
  tEntry("FRD", "tool"),
  tEntry("SRS", "tool"),
  tEntry("SOP", "tool"),
  tEntry("Work instructions", "tool"),
  tEntry("Runbooks", "tool"),
  tEntry("Checklists", "tool"),
  tEntry("Templates", "tool"),
  tEntry("Spreadsheets", "tool"),
  tEntry("Pivot tables", "tool"),
  tEntry("VLOOKUP", "tool"),
  tEntry("Macros", "tool"),
  tEntry("Status reports", "tool"),
  tEntry("RAID logs", "tool"),
  tEntry("Issue logs", "tool"),
  tEntry("Risk registers", "tool"),
  tEntry("Action trackers", "tool"),
  tEntry("Meeting minutes", "tool"),
  tEntry("Decision logs", "tool"),
  tEntry("Change requests", "tool"),
  tEntry("CR forms", "tool"),
  tEntry("Sign-off forms", "tool"),
  tEntry("Training materials", "tool"),
  tEntry("Job aids", "tool"),
  tEntry("FAQs", "tool"),
  tEntry("Knowledge base articles", "tool"),
  tEntry("SQL queries", "tool"),
  tEntry("Ad-hoc reports", "tool"),
  tEntry("Canned reports", "tool"),
  tEntry("Batch reports", "tool"),
  tEntry("Interface specs", "tool"),
  tEntry("File layouts", "tool"),
  tEntry("Data dictionaries", "tool"),
  tEntry("Entity relationship diagrams", "tool", { aliases: ["ERD"] }),
  tEntry("Data models", "tool"),
  tEntry("CRUD matrices", "tool"),
  tEntry("Screen designs", "tool"),
  tEntry("Menu designs", "tool"),
  tEntry("Form designs", "tool"),
  tEntry("Validation rules", "tool"),
  tEntry("Business rules", "tool"),
  tEntry("Acceptance criteria", "tool"),
  tEntry("Defect logs", "tool"),
  tEntry("Bug trackers", "tool"),
  tEntry("Configuration workbooks", "tool"),
  tEntry("Cutover checklists", "tool"),
  tEntry("Go-live checklists", "tool"),
  tEntry("Hypercare logs", "tool"),
  tEntry("Support tickets", "tool"),
  tEntry("Service requests", "tool"),
  tEntry("UNIX", "tool"),
  tEntry("Windows OS", "tool"),
  tEntry("Client-server", "tool"),
  tEntry("Terminal emulation", "tool"),
  tEntry("FTP", "tool"),
  tEntry("SFTP", "tool"),
  tEntry("Telnet", "tool"),
  tEntry("Email clients", "tool"),
  tEntry("Calendar tools", "tool"),
  tEntry("Shared drives", "tool"),
  tEntry("Network shares", "tool"),
  tEntry("Print services", "tool"),
  tEntry("Fax workflows", "tool"),
  tEntry("Scanner workflows", "tool"),
  tEntry("Barcode labels", "tool"),
  tEntry("Forms processing", "tool"),
  tEntry("Document control", "tool"),
  tEntry("Version control (docs)", "tool"),
  tEntry("HTML", "tool"),
  tEntry("CSS", "tool"),
  tEntry("Java basics", "tool"),
  tEntry("C/C++", "tool"),
  tEntry("VB", "tool", { aliases: ["Visual Basic"] }),
  tEntry("Scripting", "tool"),
  tEntry("Batch scripts", "tool"),
  tEntry("Shell scripts", "tool"),
  tEntry("Query tools", "tool"),
  tEntry("TOAD", "tool"),
  tEntry("SQL*Plus", "tool"),
  tEntry("Query Analyzer", "tool"),
  tEntry("Crystal Reports classic", "tool"),
  tEntry("Report Writer", "tool"),
  tEntry("OLAP views", "tool"),
  tEntry("Cubes", "tool"),
  tEntry("Star schema concepts", "tool"),
  tEntry("Normalization", "tool"),
  tEntry("Referential integrity", "tool"),
  tEntry("Indexes", "tool"),
  tEntry("Stored procedures", "tool"),
  tEntry("Triggers", "tool"),
  tEntry("Views", "tool"),
  tEntry("Jobs/schedulers", "tool"),
  tEntry("Cron", "tool"),
  tEntry("Control-M concepts", "tool"),
  tEntry("MQ messaging concepts", "tool"),
  tEntry("EDI maps", "tool"),
  tEntry("Flat file interfaces", "tool"),
  tEntry("CSV interfaces", "tool"),
  tEntry("XML messages", "tool"),
  tEntry("API concepts", "tool"),
  tEntry("Web services concepts", "tool"),
  tEntry("Middleware concepts", "tool"),
  tEntry("ERP concepts", "tool"),
  tEntry("CRM concepts", "tool"),
  tEntry("HCM concepts", "tool"),
  tEntry("SCM concepts", "tool"),
  tEntry("GL concepts", "tool"),
  tEntry("AP concepts", "tool"),
  tEntry("AR concepts", "tool"),
  tEntry("Inventory concepts", "tool"),
  tEntry("Order management concepts", "tool"),
  tEntry("Billing concepts", "tool"),
  tEntry("Payroll concepts", "tool"),
  tEntry("Security roles", "tool"),
  tEntry("User provisioning", "tool"),
  tEntry("Password policies", "tool"),
  tEntry("Backup concepts", "tool"),
  tEntry("DR concepts", "tool"),
  tEntry("Capacity concepts", "tool"),
  tEntry("Performance concepts", "tool"),
  tEntry("SLA concepts", "tool"),
  tEntry("KPI metrics", "tool"),
  tEntry("Scorecards", "tool"),
  tEntry("Balanced scorecard", "tool"),
];

const TIMELESS_PLATFORMS: CatalogEntry[] = [
  tEntry("Windows desktop", "platform"),
  tEntry("Windows", "platform"),
  tEntry("LAN", "platform"),
  tEntry("WAN", "platform"),
  tEntry("Intranet", "platform"),
  tEntry("Extranet", "platform"),
  tEntry("Email system", "platform"),
  tEntry("File server", "platform"),
  tEntry("Print server", "platform"),
  tEntry("Domain network", "platform"),
  tEntry("Test lab", "platform"),
  tEntry("Training room", "platform"),
  tEntry("War room", "platform"),
  tEntry("Command center", "platform"),
  tEntry("Shared services", "platform"),
  tEntry("Offshore delivery center", "platform"),
  tEntry("Onsite client floor", "platform"),
  tEntry("Cube farm", "platform"),
  tEntry("Secure room", "platform"),
  tEntry("Tape backup library", "platform"),
  tEntry("Mainframe terminal", "platform"),
  tEntry("Green screen", "platform"),
  tEntry("Thick client", "platform"),
  tEntry("Thin client", "platform"),
  tEntry("Browser (IE era)", "platform"),
  tEntry("Citrix published apps", "platform"),
  tEntry("Remote desktop classic", "platform"),
  tEntry("VPN dial-up era", "platform"),
  tEntry("Leased line", "platform"),
  tEntry("Frame relay", "platform"),
  tEntry("Staging server", "platform"),
  tEntry("Dev server", "platform"),
  tEntry("QA server", "platform"),
  tEntry("UAT server", "platform"),
  tEntry("Prod server", "platform"),
  tEntry("Cluster (classic)", "platform"),
  tEntry("Load balancer classic", "platform"),
  tEntry("DMZ classic", "platform"),
  tEntry("Firewall classic", "platform"),
  tEntry("Proxy classic", "platform"),
  tEntry("Directory services classic", "platform"),
  tEntry("NT domain", "platform"),
  tEntry("Novell", "platform"),
  tEntry("AS/400 green screen", "platform"),
  tEntry("Unix host", "platform"),
  tEntry("Solaris host", "platform"),
  tEntry("AIX host", "platform"),
  tEntry("HP-UX host", "platform"),
];

const TIMELESS_PROCESSES: CatalogEntry[] = [
  tEntry("Waterfall SDLC", "process"),
  tEntry("Structured analysis", "process"),
  tEntry("Structured design", "process"),
  tEntry("JAD sessions", "process"),
  tEntry("RAD workshops", "process"),
  tEntry("Prototyping", "process"),
  tEntry("Peer review", "process"),
  tEntry("Walkthroughs", "process"),
  tEntry("Inspections", "process"),
  tEntry("Unit test execution", "process"),
  tEntry("Integration test", "process"),
  tEntry("System test", "process"),
  tEntry("User acceptance", "process"),
  tEntry("Regression suite", "process"),
  tEntry("Smoke test", "process"),
  tEntry("Sanity test", "process"),
  tEntry("Stress test classic", "process"),
  tEntry("Volume test", "process"),
  tEntry("Pilot gates", "process"),
  tEntry("Stage gates", "process"),
  tEntry("Phase exit review", "process"),
  tEntry("Steering committee", "process"),
  tEntry("Status cadence", "process"),
  tEntry("Weekly status", "process"),
  tEntry("Daily stand-up classic", "process"),
  tEntry("Issue triage", "process"),
  tEntry("Escalation path", "process"),
  tEntry("Vendor coordination", "process"),
  tEntry("Offshore coordination", "process"),
  tEntry("Onsite facilitation", "process"),
  tEntry("Knowledge capture", "process"),
  tEntry("Shadow training", "process"),
  tEntry("Classroom training", "process"),
  tEntry("CBT materials", "process"),
  tEntry("Pilot rollout", "process"),
  tEntry("Phased rollout classic", "process"),
  tEntry("Big-bang go-live", "process"),
  tEntry("Parallel run classic", "process"),
  tEntry("Data conversion", "process"),
  tEntry("Data cleansing", "process"),
  tEntry("Data validation", "process"),
  tEntry("Reconciliation classic", "process"),
  tEntry("Mock conversion classic", "process"),
  tEntry("Dress rehearsal classic", "process"),
  tEntry("Cutover weekend", "process"),
  tEntry("Warranty support classic", "process"),
  tEntry("BAU handover classic", "process"),
  tEntry("Lessons learned classic", "process"),
  tEntry("Continuous improvement classic", "process"),
  tEntry("Root cause classic", "process"),
  tEntry("5 Whys", "process"),
  tEntry("Fishbone analysis", "process"),
  tEntry("Pareto analysis", "process"),
  tEntry("RACI classic", "process"),
  tEntry("RAID classic", "process"),
  tEntry("MoSCoW prioritization", "process"),
  tEntry("Impact analysis classic", "process"),
  tEntry("Scope control", "process"),
  tEntry("Baseline management", "process"),
  tEntry("Configuration management classic", "process"),
  tEntry("Document control classic", "process"),
  tEntry("Version control classic", "process"),
  tEntry("Release notes classic", "process"),
  tEntry("CAB classic", "process"),
  tEntry("Change board", "process"),
  tEntry("Incident process classic", "process"),
  tEntry("Problem process classic", "process"),
  tEntry("Request fulfillment", "process"),
  tEntry("Service desk process", "process"),
  tEntry("ITIL classic", "process"),
  tEntry("PMBOK practices", "process"),
  tEntry("PRINCE2 practices", "process"),
  tEntry("CMMI practices", "process"),
  tEntry("Six Sigma basics", "process"),
  tEntry("Lean basics", "process"),
  tEntry("Kaizen", "process"),
  tEntry("Value stream classic", "process"),
];

const TIMELESS_COMPLIANCE: CatalogEntry[] = [
  tEntry("Password standards", "compliance"),
  tEntry("Access request process", "compliance"),
  tEntry("User access reviews", "compliance"),
  tEntry("Role design", "compliance"),
  tEntry("SoD checks classic", "compliance"),
  tEntry("Audit support classic", "compliance"),
  tEntry("Evidence retention", "compliance"),
  tEntry("Change tickets", "compliance"),
  tEntry("Approval workflows", "compliance"),
  tEntry("Maker-checker", "compliance"),
  tEntry("Four-eyes principle", "compliance"),
  tEntry("Data classification classic", "compliance"),
  tEntry("Confidentiality agreements", "compliance"),
  tEntry("Physical security", "compliance"),
  tEntry("Clean desk", "compliance"),
  tEntry("Backup verification", "compliance"),
  tEntry("Restore tests", "compliance"),
  tEntry("DR documentation", "compliance"),
  tEntry("BCP documentation", "compliance"),
  tEntry("Policy acknowledgment", "compliance"),
  tEntry("Training attestation", "compliance"),
  tEntry("Vendor NDAs", "compliance"),
  tEntry("Contract SLAs", "compliance"),
];

/** Assert no cross-kind term collisions at build time (dev safety). */
function assertDisjoint(catalog: CatalogEntry[]): CatalogEntry[] {
  const seen = new Map<string, string>();
  const out: CatalogEntry[] = [];
  for (const e of catalog) {
    const k = e.term.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
    if (!k) continue;
    const prev = seen.get(k);
    if (prev && prev !== e.kind) {
      // Skip duplicate across kinds — first kind wins
      continue;
    }
    if (prev === e.kind) continue;
    seen.set(k, e.kind);
    for (const a of e.aliases || []) {
      const ak = a.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
      if (ak && !seen.has(ak)) seen.set(ak, e.kind);
    }
    out.push(e);
  }
  return out;
}

/**
 * Era recipes — multiple variants per era so rotation never clones.
 * Stack = tools; env = platforms. Processes/compliance/regs optional flavor.
 */
export const DEFAULT_ERA_RECIPES: EraRecipe[] = [
  // ── pre-2010 ──────────────────────────────────────────────
  {
    era: "pre2010",
    stack: ["SQL", "Excel", "MS Office", "Reporting", "Word", "Visio"],
    env: ["On-premise", "Windows Server", "Client site", "LAN"],
    processes: ["Waterfall", "UAT", "Cutover planning", "SDLC"],
    compliance: ["SOX", "ITGC", "Change control"],
  },
  {
    era: "pre2010",
    stack: ["ECC", "MM", "SD", "FICO", "IDoc", "ABAP", "Excel"],
    env: ["On-premise", "HP ALM", "Data center", "Test lab"],
    processes: ["Blueprinting", "Unit testing", "Go-live", "SIT"],
    compliance: ["Change control", "SoD", "Access controls"],
  },
  {
    era: "pre2010",
    stack: ["Oracle EBS", "PL/SQL", "Data Mapping", "SQL", "Reporting"],
    env: ["On-premise", "Oracle DB", "VPN", "Staging server"],
    processes: ["Gap analysis", "SIT", "Knowledge transfer", "UAT"],
    compliance: ["Internal audit", "Access controls"],
  },
  {
    era: "pre2010",
    stack: ["Java", "SQL", "HTML", "XML", "Excel", "Test cases"],
    env: ["On-premise", "Linux", "QA server", "Citrix"],
    processes: ["SDLC", "Defect triage", "Training delivery", "Waterfall"],
    compliance: ["Audit trail", "Policy alignment"],
  },
  {
    era: "pre2010",
    stack: ["PeopleSoft", "HCM", "Excel", "VBA", "Reporting", "Word"],
    env: ["On-premise", "Windows Server", "Shared services hub", "LAN"],
    processes: ["Requirements gathering", "UAT", "Hypercare", "JAD sessions"],
    compliance: ["SOX", "Data retention"],
  },
  {
    era: "pre2010",
    stack: [
      "MS Office",
      "Excel",
      "Visio",
      "Requirements docs",
      "Test cases",
      "SQL",
      "BRD",
    ],
    env: ["On-premise", "Client site", "Windows desktop", "Test lab"],
    processes: ["Waterfall", "UAT", "Walkthroughs", "Status cadence"],
    compliance: ["Change tickets", "Access request process"],
  },
  {
    era: "pre2010",
    stack: [
      "COBOL",
      "JCL",
      "DB2",
      "CICS",
      "SQL",
      "Excel",
      "Batch scripts",
    ],
    env: ["Mainframe LPAR", "Data center", "Green screen", "On-premise"],
    processes: ["Waterfall", "System test", "Parallel run classic", "Cutover weekend"],
    compliance: ["ITGC", "Change control"],
  },
  // ── 2010–2015 ────────────────────────────────────────────
  {
    era: "2010_2015",
    stack: ["ECC", "FICO", "BW", "BPC", "ETL", "SQL"],
    env: ["On-premise", "SolMan", "Jira", "ALM"],
    processes: ["Agile", "SIT", "Release management"],
    compliance: ["SOX", "SoD"],
  },
  {
    era: "2010_2015",
    stack: ["MDM", "Data Quality", "Informatica", "REST", "SOAP"],
    env: ["Hybrid Cloud", "SQL Server", "Confluence", "Client site"],
    processes: ["Data migration", "Mock conversion", "UAT"],
    compliance: ["ITGC", "Access controls"],
  },
  {
    era: "2010_2015",
    stack: ["EWM", "WM", "MM", "IDoc", "Master Data"],
    env: ["On-premise", "HP ALM", "Transport landscape"],
    processes: ["Fit-gap", "Regression testing", "Cutover planning"],
    compliance: ["Change control", "Evidence packs"],
  },
  {
    era: "2010_2015",
    stack: ["Salesforce", "REST", "SOAP", "Reporting", "Dashboards"],
    env: ["Public Cloud", "Jira", "Git", "Remote delivery"],
    processes: ["Scrum", "Sprint planning", "Hypercare"],
    compliance: ["SOC 2", "Vendor risk"],
  },
  {
    era: "2010_2015",
    stack: ["HANA", "BW", "ABAP", "Fiori", "OData"],
    env: ["On-premise", "SolMan", "Sandbox", "ServiceNow"],
    processes: ["DevOps", "CI/CD", "Dress rehearsal"],
    compliance: ["SOX", "Least privilege"],
    regulations: ["GDPR"],
  },
  // ── 2016–2019 ────────────────────────────────────────────
  {
    era: "2016_2019",
    stack: ["S/4HANA", "Fiori", "RTR", "MDG", "OData"],
    env: ["Azure", "SolMan", "Jira", "Azure DevOps"],
    processes: ["SAFe", "UAT", "Go-live"],
    compliance: ["SOX", "ITGC"],
    regulations: ["GDPR", "IFRS 15"],
  },
  {
    era: "2016_2019",
    stack: ["ATTP", "EPCIS", "GTIN", "SSCC", "ETL"],
    env: ["AWS", "ServiceNow", "GitHub", "Staging landscape"],
    processes: ["SIT", "Performance testing", "Hypercare"],
    compliance: ["GxP", "CSV", "21 CFR Part 11"],
    regulations: ["DSCSA", "GS1 standards"],
  },
  {
    era: "2016_2019",
    stack: ["Python", "Spark", "ETL", "dbt", "Power BI"],
    env: ["Databricks", "Snowflake", "Azure", "Confluence"],
    processes: ["Agile", "Data migration", "Reconciliation cycles"],
    compliance: ["SOC 2", "Privacy by design"],
    regulations: ["CCPA"],
  },
  {
    era: "2016_2019",
    stack: ["BRIM", "FI-CA", "RAR", "OData", "SQL"],
    env: ["Private Cloud", "CPI", "Jira", "ALM"],
    processes: ["Blueprinting", "Regression testing", "CAB"],
    compliance: ["SOX", "SoD", "Audit trail"],
    regulations: ["ASC 606"],
  },
  {
    era: "2016_2019",
    stack: ["IBP", "Excel", "Data Mapping", "REST", "Reporting"],
    env: ["Azure", "Data Factory", "Git", "Remote delivery"],
    processes: ["Hybrid delivery", "Steering reporting", "Cutover planning"],
    compliance: ["Change control", "Risk assessment"],
  },
  // ── 2020+ ────────────────────────────────────────────────
  {
    era: "2020_plus",
    stack: ["S/4HANA", "Fiori", "ABAP", "OData", "REST"],
    env: ["RISE", "BTP", "Azure", "Jira", "ServiceNow"],
    processes: ["DevOps", "CI/CD", "Value stream mapping"],
    compliance: ["SOC 2", "ISO 27001"],
    regulations: ["GDPR", "CPRA"],
  },
  {
    era: "2020_plus",
    stack: ["ATTP", "EPCIS", "GTIN", "SSCC", "Kafka"],
    env: ["AWS", "Databricks", "GitHub", "Remote delivery"],
    processes: ["SAFe", "UAT", "Hypercare"],
    compliance: ["GxP", "Data integrity ALCOA+", "CSV"],
    regulations: ["DSCSA", "FMD", "EU MDR"],
  },
  {
    era: "2020_plus",
    stack: ["Python", "PySpark", "dbt", "Kafka", "Power BI"],
    env: ["Snowflake", "Synapse", "Kubernetes", "Azure DevOps"],
    processes: ["Process mining", "Agile", "Incident management"],
    compliance: ["NIST", "Encryption standards"],
    regulations: ["CCPA", "State privacy acts"],
  },
  {
    era: "2020_plus",
    stack: ["Workday", "HCM", "REST", "Reporting", "Dashboards"],
    env: ["Public Cloud", "Active Directory", "Jira", "Confluence"],
    processes: ["Change management", "Train-the-trainer", "Adoption tracking"],
    compliance: ["SOC 2", "Least privilege", "Access controls"],
    regulations: ["HIPAA", "GDPR"],
  },
  {
    era: "2020_plus",
    stack: ["Dynamics 365", "REST", "Power BI", "Data Mapping", "SQL"],
    env: ["Azure", "Logic Apps", "GitHub", "Prod landscape"],
    processes: ["Scrum", "Release management", "Lessons learned"],
    compliance: ["SOX", "Business continuity"],
    regulations: ["PCI-DSS"],
  },
  // ── Extra recipes per era (rotation depth) ─────────────────
  {
    era: "pre2010",
    stack: ["Mainframe", "COBOL", "JCL", "DB2", "CICS"],
    env: ["Mainframe LPAR", "Data center", "Hot standby", "File servers"],
    processes: ["Waterfall", "Parallel run", "Ops handover"],
    compliance: ["ITGC", "Change control"],
  },
  {
    era: "pre2010",
    stack: ["EDI", "X12", "EDIFACT", "XML", "Flat files"],
    env: ["On-premise", "Partner portal", "VPN", "Staging landscape"],
    processes: ["Interface mapping", "SIT", "Defect triage"],
    compliance: ["Audit trail", "Interface controls"],
  },
  {
    era: "pre2010",
    stack: ["Siebel", "CRM", "Java", "SOAP", "Crystal Reports"],
    env: ["On-premise", "Citrix", "Windows Server", "Client site"],
    processes: ["Blueprinting", "UAT", "Training delivery"],
    compliance: ["Access controls", "SOX"],
  },
  {
    era: "pre2010",
    stack: ["Hyperion", "Essbase", "Excel", "VBA", "Reporting"],
    env: ["On-premise", "Shared services hub", "SQL Server", "Print servers"],
    processes: ["Requirements gathering", "Reconciliation cycles", "Go-live"],
    compliance: ["SOX", "Evidence packs"],
  },
  {
    era: "2010_2015",
    stack: ["MuleSoft", "REST", "SOAP", "JSON", "Data Mapping"],
    env: ["iPaaS tenant", "Hybrid Cloud", "Jira", "Confluence"],
    processes: ["Agile", "Interface partner call", "Hypercare"],
    compliance: ["SOC 2", "Vendor risk"],
  },
  {
    era: "2010_2015",
    stack: ["Workday", "HCM", "REST", "Reporting", "Excel"],
    env: ["Workday tenant", "Public Cloud", "Remote delivery", "ServiceNow"],
    processes: ["Change management", "UAT", "Train-the-trainer"],
    compliance: ["SOX", "Access controls"],
    regulations: ["HIPAA"],
  },
  {
    era: "2010_2015",
    stack: ["Tableau", "SQL", "ETL", "Data Quality", "Dashboards"],
    env: ["On-premise", "SQL Server", "SharePoint on-prem", "ALM"],
    processes: ["Scrum", "Sprint planning", "Release management"],
    compliance: ["ITGC", "Least privilege"],
  },
  {
    era: "2010_2015",
    stack: ["NetSuite", "ERP", "REST", "Bank feeds", "Reconciliation"],
    env: ["Multi-tenant SaaS", "Remote delivery", "Git", "Sandbox tenant"],
    processes: ["Fit-gap", "Cutover planning", "Hypercare"],
    compliance: ["SOC 1", "Change control"],
  },
  {
    era: "2016_2019",
    stack: ["RPA", "UiPath", "Excel", "Workflow automation", "REST"],
    env: ["Azure", "VDI", "Jira Cloud", "Teams"],
    processes: ["Agile", "Pilot gate review", "Phased rollout"],
    compliance: ["SOX", "SoD"],
  },
  {
    era: "2016_2019",
    stack: ["Salesforce", "Service Cloud", "REST", "Reporting", "Dashboards"],
    env: ["Salesforce org", "Salesforce sandbox", "Slack", "GitHub"],
    processes: ["Scrum", "Backlog refinement", "Adoption tracking"],
    compliance: ["SOC 2", "Privacy by design"],
    regulations: ["GDPR"],
  },
  {
    era: "2016_2019",
    stack: ["Python", "dbt", "SQL", "Power BI", "Airflow DAGs"],
    env: ["Snowflake", "AWS", "Confluence", "Remote delivery"],
    processes: ["Data migration", "Reconciliation cycles", "CI/CD"],
    compliance: ["SOC 2", "Encryption standards"],
    regulations: ["CCPA"],
  },
  {
    era: "2016_2019",
    stack: ["Helm charts", "REST", "Microservices patterns", "JSON", "GraphQL"],
    env: ["EKS", "Docker", "GitLab", "Kubernetes"],
    processes: ["DevOps", "Canary release", "Postmortem"],
    compliance: ["Secure SDLC", "Vulnerability management"],
  },
  {
    era: "2020_plus",
    stack: ["FastAPI", "Python", "Kafka", "Grafana", "OpenAPI"],
    env: ["GKE", "Kubernetes", "GitHub", "SIEM console"],
    processes: ["Trunk-based development", "Progressive delivery", "Site reliability practices"],
    compliance: ["ISO 27001", "SBOM discipline"],
    regulations: ["NIS2"],
  },
  {
    era: "2020_plus",
    stack: ["REST", "Power BI", "SharePoint", "Data Mapping", "SQL"],
    env: ["Power Platform", "Dataverse environment", "Teams", "Azure AD"],
    processes: ["Architecture review board", "CAB", "Wave planning"],
    compliance: ["SOX", "Access controls"],
  },
  {
    era: "2020_plus",
    stack: ["FHIR", "HL7", "REST", "JSON", "ETL"],
    env: ["Azure", "API gateway", "Private Cloud", "ServiceNow"],
    processes: ["Privacy impact assessment", "UAT", "Hypercare"],
    compliance: ["HITRUST", "Encryption standards"],
    regulations: ["HIPAA", "HITECH"],
  },
  {
    era: "2020_plus",
    stack: ["LLM orchestration", "RAG patterns", "Python", "Vector search", "API design"],
    env: ["Azure", "Kubernetes", "Feature environments", "GitHub"],
    processes: ["Shift-left testing", "Threat modeling", "Architecture review board"],
    compliance: ["Model risk management", "Responsible AI program", "Ethics review board"],
    regulations: ["AI Act", "GDPR"],
  },
  {
    era: "2020_plus",
    stack: ["Anaplan", "Excel", "Data Mapping", "Dashboards", "KPI Design"],
    env: ["Public Cloud", "Okta", "Jira", "Confluence"],
    processes: ["OKR alignment", "Steering reporting", "Value realization"],
    compliance: ["SOX", "Internal control framework"],
    regulations: ["IFRS 15"],
  },
];

export const DEFAULT_STACK_ENV_BANK: StackEnvBankDoc = {
  version: 1,
  catalog: assertDisjoint([
    // Timeless first so first-kind wins on any accidental collision
    ...TIMELESS_TOOLS,
    ...TIMELESS_PLATFORMS,
    ...TIMELESS_PROCESSES,
    ...TIMELESS_COMPLIANCE,
    ...TOOLS,
    ...PLATFORMS,
    ...PROCESSES,
    ...COMPLIANCE,
    ...REGULATIONS,
  ]),
  recipes: DEFAULT_ERA_RECIPES,
};

/** Counts for admin UI */
export function bankStats(doc: StackEnvBankDoc = DEFAULT_STACK_ENV_BANK) {
  const byKind: Record<string, number> = {};
  for (const e of doc.catalog) {
    byKind[e.kind] = (byKind[e.kind] || 0) + 1;
  }
  return {
    total: doc.catalog.length,
    byKind,
    recipes: doc.recipes.length,
  };
}
